# Generated by Django 5.2.5 on 2025-08-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=2)),
                ('phone', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('todo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo_list.todo')),
            ],
        ),
    ]
