# Generated by Django 5.2.5 on 2025-08-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_todo_id_alter_users_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
