# Generated by Django 5.2.5 on 2025-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_age_remove_users_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=False, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
