# Generated by Django 5.2.5 on 2025-09-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_remove_todo_updated_at_todo_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='completed',
        ),
    ]
